"""Expense API URLs."""

from django.urls import path

from expense.views import (
    ExpenseStatsAPIView,
    ExpenseConfigAPIView,
    ExpenseGroupDetailAPIView,
    ExpenseGroupExportAPIView,
    ExpenseGroupItemsAPIView,
    ExpenseGroupListAPIView,
    ExpenseGroupSummaryAPIView,
    ExpenseInvoiceDetailAPIView,
    ExpenseInvoiceFileAPIView,
    ExpenseInvoiceFileAwayAPIView,
    ExpenseInvoiceListAPIView,
    ExpenseNamingAPIView,
    ExpenseInvoiceReextractAPIView,
    ExpenseLinkAllowAPIView,
    ExpenseLinkListAPIView,
    ExpenseScanAPIView,
    ExpenseScanPreviewAPIView,
    ExpenseScanRunDetailAPIView,
    ExpenseScanRunListAPIView,
    ExpenseTripAcceptAPIView,
    ExpenseTripDismissAPIView,
    ExpenseTripListAPIView,
)


urlpatterns = [
    path(
        "apps/expense/config",
        ExpenseConfigAPIView.as_view(),
        name="expense-config",
    ),
    path(
        "apps/expense/stats",
        ExpenseStatsAPIView.as_view(),
        name="expense-stats",
    ),
    path(
        "apps/expense/scan",
        ExpenseScanAPIView.as_view(),
        name="expense-scan",
    ),
    path(
        "apps/expense/scan/preview",
        ExpenseScanPreviewAPIView.as_view(),
        name="expense-scan-preview",
    ),
    path(
        "apps/expense/scan-runs",
        ExpenseScanRunListAPIView.as_view(),
        name="expense-scan-runs",
    ),
    path(
        "apps/expense/scan-runs/<uuid:uuid>",
        ExpenseScanRunDetailAPIView.as_view(),
        name="expense-scan-run-detail",
    ),
    path(
        "apps/expense/invoices",
        ExpenseInvoiceListAPIView.as_view(),
        name="expense-invoices",
    ),
    path(
        "apps/expense/invoices/file-away",
        ExpenseInvoiceFileAwayAPIView.as_view(),
        name="expense-invoice-file-away",
    ),
    path(
        "apps/expense/invoices/<uuid:uuid>",
        ExpenseInvoiceDetailAPIView.as_view(),
        name="expense-invoice-detail",
    ),
    path(
        "apps/expense/invoices/<uuid:uuid>/reextract",
        ExpenseInvoiceReextractAPIView.as_view(),
        name="expense-invoice-reextract",
    ),
    path(
        "apps/expense/invoices/<uuid:uuid>/file",
        ExpenseInvoiceFileAPIView.as_view(),
        name="expense-invoice-file",
    ),
    path(
        "apps/expense/groups",
        ExpenseGroupListAPIView.as_view(),
        name="expense-groups",
    ),
    path(
        "apps/expense/groups/<uuid:uuid>",
        ExpenseGroupDetailAPIView.as_view(),
        name="expense-group-detail",
    ),
    path(
        "apps/expense/groups/<uuid:uuid>/items",
        ExpenseGroupItemsAPIView.as_view(),
        name="expense-group-items",
    ),
    path(
        "apps/expense/groups/<uuid:uuid>/summary",
        ExpenseGroupSummaryAPIView.as_view(),
        name="expense-group-summary",
    ),
    path(
        "apps/expense/groups/<uuid:uuid>/export",
        ExpenseGroupExportAPIView.as_view(),
        name="expense-group-export",
    ),
    path(
        "apps/expense/trips",
        ExpenseTripListAPIView.as_view(),
        name="expense-trips",
    ),
    path(
        "apps/expense/trips/<uuid:uuid>/accept",
        ExpenseTripAcceptAPIView.as_view(),
        name="expense-trip-accept",
    ),
    path(
        "apps/expense/trips/<uuid:uuid>/dismiss",
        ExpenseTripDismissAPIView.as_view(),
        name="expense-trip-dismiss",
    ),
    path(
        "apps/expense/naming",
        ExpenseNamingAPIView.as_view(),
        name="expense-naming",
    ),
    path(
        "apps/expense/links",
        ExpenseLinkListAPIView.as_view(),
        name="expense-links",
    ),
    path(
        "apps/expense/links/<uuid:uuid>/allow",
        ExpenseLinkAllowAPIView.as_view(),
        name="expense-link-allow",
    ),
]
