# Generated by Django 5.1.4 on 2026-08-30 03:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0015_billingconfig_invoice_email_cost_credits"),
        ("threadline", "0037_emailmessage_merge_evidence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseAppConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workflow_key",
                    models.CharField(
                        default="expense",
                        max_length=64,
                        unique=True,
                        verbose_name="Workflow Key",
                    ),
                ),
                (
                    "llm_config_uuid",
                    models.UUIDField(
                        blank=True,
                        help_text="Used for images and scanned documents without a text layer",
                        null=True,
                        verbose_name="Vision LLM Config UUID",
                    ),
                ),
                (
                    "text_llm_config_uuid",
                    models.UUIDField(
                        blank=True,
                        help_text="Used for PDF/OFD files that carry a usable text layer",
                        null=True,
                        verbose_name="Text LLM Config UUID",
                    ),
                ),
                (
                    "scan_schedule",
                    models.CharField(
                        default="0 3 * * *",
                        help_text="5-field cron expression driving the periodic scan",
                        max_length=255,
                        verbose_name="Scan Schedule",
                    ),
                ),
                (
                    "max_pdf_pages",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Max PDF Pages"
                    ),
                ),
                (
                    "link_domain_allowlist",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Domains allowed for body-link downloads",
                        verbose_name="Link Domain Allowlist",
                    ),
                ),
                (
                    "max_download_bytes",
                    models.PositiveIntegerField(
                        default=20971520, verbose_name="Max Download Bytes"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Expense App Config",
                "verbose_name_plural": "Expense App Configs",
            },
        ),
        migrations.CreateModel(
            name="ExpenseGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("purpose", models.TextField(blank=True, verbose_name="Purpose")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("reimbursed", "Reimbursed"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                (
                    "trip_type",
                    models.CharField(
                        choices=[
                            ("business_trip", "Business Trip"),
                            ("daily", "Daily"),
                        ],
                        default="daily",
                        max_length=32,
                        verbose_name="Trip Type",
                    ),
                ),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                (
                    "external_ref",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="External Reference"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                ("invoice_count", models.PositiveIntegerField(default=0)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("exported_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Group",
                "verbose_name_plural": "Expense Groups",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseUserConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False, verbose_name="Enabled")),
                (
                    "enabled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Scans only look at mail received after this point",
                        null=True,
                        verbose_name="Enabled At",
                    ),
                ),
                (
                    "last_scanned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Scanned At"
                    ),
                ),
                (
                    "home_city",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to infer from recent invoices",
                        max_length=64,
                        verbose_name="Home City",
                    ),
                ),
                (
                    "sender_allowlist",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Sender Allowlist"
                    ),
                ),
                (
                    "keyword_filters",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Keyword Filters"
                    ),
                ),
                (
                    "filename_template",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Filename Template"
                    ),
                ),
                (
                    "extra_link_domains",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Extra Link Domains"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_config",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense User Config",
                "verbose_name_plural": "Expense User Configs",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("attachment", "Attachment"),
                            ("body_link", "Body Link"),
                            ("nested_eml", "Nested EML"),
                        ],
                        default="attachment",
                        max_length=32,
                        verbose_name="Source Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("extracting", "Extracting"),
                            ("extracted", "Extracted"),
                            ("duplicate", "Duplicate"),
                            ("not_invoice", "Not An Invoice"),
                            ("failed", "Failed"),
                            ("insufficient_credits", "Insufficient Credits"),
                            ("link_requires_auth", "Link Requires Auth"),
                            ("pending_dependency", "Pending Dependency"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("vat_special", "VAT Special Invoice"),
                            ("vat_normal", "VAT Normal Invoice"),
                            ("vat_electronic", "VAT Electronic Invoice"),
                            ("train", "Train Ticket"),
                            ("flight_itinerary", "Flight Itinerary"),
                            ("coach", "Coach Ticket"),
                            ("taxi", "Taxi Receipt"),
                            ("hotel", "Hotel Invoice"),
                            ("quota", "Quota Invoice"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                        verbose_name="Invoice Type",
                    ),
                ),
                (
                    "invoice_no",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Invoice Number"
                    ),
                ),
                (
                    "invoice_code",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Invoice Code"
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(blank=True, null=True, verbose_name="Issue Date"),
                ),
                (
                    "seller_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Seller Name"
                    ),
                ),
                (
                    "seller_tax_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Seller Tax ID"
                    ),
                ),
                (
                    "buyer_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Buyer Name"
                    ),
                ),
                (
                    "buyer_tax_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Buyer Tax ID"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Total Amount",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Tax Amount",
                    ),
                ),
                (
                    "amount_excl_tax",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Amount Excluding Tax",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="CNY", max_length=8, verbose_name="Currency"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("transport_long", "Long-distance Transport"),
                            ("transport_local", "Local Transport"),
                            ("accommodation", "Accommodation"),
                            ("meals", "Meals"),
                            ("entertainment", "Entertainment"),
                            ("office", "Office Supplies"),
                            ("communication", "Communication"),
                            ("training", "Training"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                        verbose_name="Category",
                    ),
                ),
                (
                    "category_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rule", "Ticket Type Rule"),
                            ("user_rule", "User Rule"),
                            ("model", "Model"),
                            ("user", "User Correction"),
                        ],
                        max_length=16,
                        verbose_name="Category Source",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="Where the expense happened; drives trip clustering",
                        max_length=64,
                        verbose_name="City",
                    ),
                ),
                (
                    "items",
                    models.JSONField(blank=True, default=list, verbose_name="Items"),
                ),
                (
                    "ticket_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Non-standard ticket fields such as train or flight info",
                        verbose_name="Ticket Details",
                    ),
                ),
                (
                    "raw_extraction",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Raw Extraction"
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(blank=True, null=True, verbose_name="Confidence"),
                ),
                (
                    "needs_review",
                    models.BooleanField(default=False, verbose_name="Needs Review"),
                ),
                (
                    "verification_status",
                    models.CharField(
                        default="unverified",
                        max_length=32,
                        verbose_name="Verification Status",
                    ),
                ),
                (
                    "dedup_key",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=128,
                        null=True,
                        verbose_name="Dedup Key",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="Error")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "credits_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="billing.emailcreditstransaction",
                        verbose_name="Credits Transaction",
                    ),
                ),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="expense.invoice",
                        verbose_name="Duplicate Of",
                    ),
                ),
                (
                    "email_attachment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="threadline.emailattachment",
                        verbose_name="Email Attachment",
                    ),
                ),
                (
                    "email_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="threadline.emailmessage",
                        verbose_name="Email Message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ["-issue_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseGroupItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="expense.expensegroup",
                        verbose_name="Group",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_items",
                        to="expense.invoice",
                        verbose_name="Invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Group Item",
                "verbose_name_plural": "Expense Group Items",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceScanRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("manual", "Manual"),
                            ("backfill", "Backfill"),
                        ],
                        default="scheduled",
                        max_length=32,
                        verbose_name="Trigger",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("emails_scanned", models.PositiveIntegerField(default=0)),
                ("candidate_emails", models.PositiveIntegerField(default=0)),
                ("links_fetched", models.PositiveIntegerField(default=0)),
                ("invoices_created", models.PositiveIntegerField(default=0)),
                ("duplicates", models.PositiveIntegerField(default=0)),
                ("not_invoice", models.PositiveIntegerField(default=0)),
                ("failed", models.PositiveIntegerField(default=0)),
                ("credits_consumed", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_scan_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Scan Run",
                "verbose_name_plural": "Invoice Scan Runs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceSourceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "source_url",
                    models.URLField(max_length=1000, verbose_name="Source URL"),
                ),
                (
                    "final_url",
                    models.URLField(
                        blank=True, max_length=1000, verbose_name="Final URL"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Content Type"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(default=0, verbose_name="File Size"),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="File Path"
                    ),
                ),
                (
                    "content_md5",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=32,
                        verbose_name="Content MD5",
                    ),
                ),
                (
                    "fetch_status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("blocked_domain", "Blocked Domain"),
                            ("blocked_ip", "Blocked IP"),
                            ("too_large", "Too Large"),
                            ("timeout", "Timeout"),
                            ("requires_auth", "Requires Auth"),
                            ("bad_type", "Bad Content Type"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="ok",
                        max_length=32,
                        verbose_name="Fetch Status",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="Error")),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_source_files",
                        to="threadline.emailmessage",
                        verbose_name="Email Message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_source_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Source File",
                "verbose_name_plural": "Invoice Source Files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="source_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="expense.invoicesourcefile",
                verbose_name="Source File",
            ),
        ),
        migrations.CreateModel(
            name="TripSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "destination_city",
                    models.CharField(max_length=64, verbose_name="Destination City"),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                ("invoice_ids", models.JSONField(blank=True, default=list)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("confidence", models.FloatField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("suggested", "Suggested"),
                            ("accepted", "Accepted"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="suggested",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accepted_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trip_suggestions",
                        to="expense.expensegroup",
                        verbose_name="Accepted Group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_suggestions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip Suggestion",
                "verbose_name_plural": "Trip Suggestions",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="CategoryRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("seller_name", "Seller Name"),
                            ("seller_tax_id", "Seller Tax ID"),
                            ("invoice_type", "Invoice Type"),
                        ],
                        default="seller_name",
                        max_length=32,
                        verbose_name="Match Type",
                    ),
                ),
                (
                    "match_value",
                    models.CharField(max_length=255, verbose_name="Match Value"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("transport_long", "Long-distance Transport"),
                            ("transport_local", "Local Transport"),
                            ("accommodation", "Accommodation"),
                            ("meals", "Meals"),
                            ("entertainment", "Entertainment"),
                            ("office", "Office Supplies"),
                            ("communication", "Communication"),
                            ("training", "Training"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                        verbose_name="Category",
                    ),
                ),
                (
                    "hit_count",
                    models.PositiveIntegerField(default=0, verbose_name="Hit Count"),
                ),
                (
                    "created_from",
                    models.CharField(
                        choices=[
                            ("user_correction", "User Correction"),
                            ("preset", "Preset"),
                        ],
                        default="user_correction",
                        max_length=32,
                        verbose_name="Created From",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_category_rules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category Rule",
                "verbose_name_plural": "Category Rules",
                "ordering": ["-updated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "match_type", "match_value"),
                        name="expense_category_rule_uniq",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="expensegroup",
            index=models.Index(
                fields=["user", "status"], name="expense_exp_user_id_f9a5a6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="expensegroup",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="expense_group_user_name_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="expenseuserconfig",
            index=models.Index(
                fields=["enabled"], name="expense_exp_enabled_e01b12_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="expensegroupitem",
            constraint=models.UniqueConstraint(
                fields=("group", "invoice"), name="expense_group_item_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="invoicescanrun",
            index=models.Index(
                fields=["user", "status"], name="expense_inv_user_id_a4a65d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoicesourcefile",
            index=models.Index(
                fields=["user", "fetch_status"], name="expense_inv_user_id_e63842_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["user", "status"], name="expense_inv_user_id_aaae3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["user", "issue_date"], name="expense_inv_user_id_d0520b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["user", "category"], name="expense_inv_user_id_4acd6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["user", "city", "issue_date"],
                name="expense_inv_user_id_869c7d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("user", "dedup_key"), name="expense_invoice_user_dedup_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("email_attachment",), name="expense_invoice_attachment_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="tripsuggestion",
            index=models.Index(
                fields=["user", "status"], name="expense_tri_user_id_326757_idx"
            ),
        ),
    ]
