# Generated by Django 5.1.4 on 2026-08-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicesourcefile",
            name="user_allowed",
            field=models.BooleanField(
                default=False,
                help_text="Set when the user releases a single link whose domain is not on the allowlist",
                verbose_name="User Allowed",
            ),
        ),
    ]
