# Generated by Django 5.1.4 on 2026-08-31 02:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0015_billingconfig_invoice_email_cost_credits"),
        ("expense", "0002_invoicesourcefile_user_allowed"),
        ("threadline", "0039_migrate_imap_config_to_mailbox"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="expense_date",
            field=models.DateField(
                blank=True,
                help_text="Travel or consumption date; falls back to issue date",
                null=True,
                verbose_name="Expense Date",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["user", "expense_date"], name="expense_inv_user_id_a922f8_idx"
            ),
        ),
    ]
