# Generated by Django 5.1.4 on 2026-08-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0004_backfill_expense_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="disposition",
            field=models.CharField(
                choices=[("to_claim", "To Claim"), ("filed", "Filed, Not Claimed")],
                db_index=True,
                default="to_claim",
                max_length=16,
                verbose_name="Disposition",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="filed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="filed_reason",
            field=models.CharField(
                blank=True,
                help_text="Why it will not be claimed: personal, rejected, expired",
                max_length=32,
                verbose_name="Filed Reason",
            ),
        ),
    ]
