# Generated by Django 5.1.4 on 2026-08-31 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0005_invoice_disposition_invoice_filed_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expenseuserconfig",
            name="extra_link_domains",
        ),
    ]
