# Generated by Django 5.1.4 on 2026-09-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0006_remove_expenseuserconfig_extra_link_domains"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenseuserconfig",
            name="home_city",
            field=models.CharField(
                blank=True,
                help_text="Where trips start and end. Blank means no trip suggestions: a trip is a journey out of this city and back",
                max_length=64,
                verbose_name="Home City",
            ),
        ),
    ]
