# Generated by Django 5.1.4 on 2026-09-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0008_canonical_suggestion_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="disposition",
            field=models.CharField(
                choices=[
                    ("to_claim", "To Claim"),
                    ("filed", "Filed, Not Claimed"),
                    ("supporting", "Supporting Document"),
                ],
                db_index=True,
                default="to_claim",
                max_length=16,
                verbose_name="Disposition",
            ),
        ),
    ]
