# Generated by Django 5.1.4 on 2026-08-30 09:21

import billing.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threadline", "0037_emailmessage_merge_evidence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailMailbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Label shown in the UI; defaults to the address",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "imap_host",
                    models.CharField(max_length=255, verbose_name="IMAP Host"),
                ),
                (
                    "imap_port",
                    models.PositiveIntegerField(default=993, verbose_name="IMAP Port"),
                ),
                ("use_ssl", models.BooleanField(default=True, verbose_name="Use SSL")),
                ("username", models.CharField(max_length=255, verbose_name="Username")),
                ("password", billing.fields.EncryptedTextField(blank=True, default="")),
                (
                    "folder",
                    models.CharField(
                        default="INBOX", max_length=100, verbose_name="Folder"
                    ),
                ),
                (
                    "delete_after_fetch",
                    models.BooleanField(
                        default=False, verbose_name="Delete After Fetch"
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Enabled")),
                (
                    "last_fetched_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Fetched At"
                    ),
                ),
                (
                    "last_success_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Success At"
                    ),
                ),
                ("last_error", models.TextField(blank=True, verbose_name="Last Error")),
                (
                    "consecutive_failures",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Consecutive Failures"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailboxes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Mailbox",
                "verbose_name_plural": "Email Mailboxes",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["enabled"], name="threadline__enabled_9b92df_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "imap_host", "username"),
                        name="threadline_mailbox_user_host_username_uniq",
                    )
                ],
            },
        ),
    ]
