# Generated by Django 5.1.4 on 2026-09-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threadline", "0039_migrate_imap_config_to_mailbox"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailmailbox",
            name="invoice_only",
            field=models.BooleanField(
                default=False,
                help_text="Fetch only the mail that names an invoice, by subject or attachment filename",
                verbose_name="Invoices Only",
            ),
        ),
    ]
