# Generated by Django 5.1.4 on 2026-09-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threadline", "0040_emailmailbox_invoice_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailmailbox",
            name="exclude_patterns",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Exclude Patterns"
            ),
        ),
        migrations.AddField(
            model_name="emailmailbox",
            name="filters",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Subject Filters"
            ),
        ),
        migrations.AddField(
            model_name="emailmailbox",
            name="max_age_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Leave empty to use the account default",
                null=True,
                verbose_name="Max Age Days",
            ),
        ),
    ]
